# -*- coding: utf-8 -*-
"""objectdetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MseFks3wGIk6ajhEb2kuK3PLqf5NGmlX
"""

!pip install ultralytics

!pip install simple_image_download==0.4

!pip install labelImg

!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

!yolo task=detect mode=train epochs=100 data=data_custom.yaml model=yolov8m.pt batch=8 patience=15

!unzip /content/train.zip -d /content/

!yolo task=detect mode=predict model=yolov8m_custom.pt show=True conf=0.5 source=1.jpeg

!yolo task=detect mode=predict model=yolov8m_custom.pt show=True conf=0.5 source=2.jpeg

!yolo task=detect mode=predict model=yolov8m_custom.pt show=True conf=0.5 source=3.jpeg

!yolo task=detect mode=predict model=yolov8m_custom.pt show=True conf=0.5 source=4.jpeg

!yolo task=detect mode=predict model=yolov8m_custom.pt show=True conf=0.5 source=6.jpeg